---
title: "Data Collection: Equity"
author: "Shannon Coulter"
date: "Last run: `r format(Sys.time(), '%F')`"
output: pdf_document
---

## TABLE OF CONTENTS
* DATASET TITLE
* AUTHORS AND AFFILIATIONS
* LANGUAGE
* SUMMARY/ABSTRACT
* KEYWORDS
* FILE ORGANIZATION
* DATASET DESCRIPTION 
* DATA DICTIONARY
* DATA ANALYSIS
* SHARING & ACCESSING INFORMATION
* ADDITIONAL NOTES/COMMENTS

### DATASET TITLE

The Equity Dashboard dataset compiled from administrative datasets located on the California Department of Education website (https://cde.ca.gov) and from local districts' student information systems (SIS)

### AUTHORS AND AFFILIATIONS

* Name: Shannon Coulter
* Organization/institution: San Diego County Office of Education
* Email: scoulter@sdcoe.net

### LANGUAGE

* English

### SUMMARY/ABSTRACT

We developed this data set to examine evidence of equity-related challenges within a school district between and among student groups. The objective of Equity Dashboard data involves populating local school dashboards schools can access as part of their equity improvement work.    


* The repository that accompanies the preprint and dataset is also available at:

  * https://github.com/scoultersdcoe/equity_dashboard

### KEYWORDS

equity; student achievement; data

### FILE ORGANIZATION

* This dataset consists of 1 folder containing XX files:
  * 1 Readme file 
  * XX files of figures/tables 
  * 67 data files 
  * 4 R script files

* For the initial input data files see script ***01_equity_import.Rmd***. 

* Each script is named for its step in the analysis process, with an additional short descriptor. 

* CSV files appended with “plot” are the exact data used for plots in article figures. 

* CSV files appended with “tab” are the exact data used for article tables.

* Files necessary to create Figures
  * Figure 1 
  * Figure 2 
  * Figure 3 
  * Figure 4 
  * Figure 5 

* Files necessary to create Tables (in article only)
  * Table 1: 
  * Table 2: 

### DATASET DESCRIPTION 

#### Data sources: 

We obtained the initial metadata through URLs via the California Department of Education's website. Over 50 administrative datasets were cleaned and combined from the California Department of Education in Testing and Accountability, Finance and Grants, and Data and Statistics. Each dataset can be accessed at https://cde.ca.gov.
We collected additional data from the local school district when administrative data were not available.

##### Administrative Data
* **Annual Enrollment** https://www.cde.ca.gov/ds/ad/filesenr.asp (files: enr20, enr19, enr18, enr17, enr16)
* **ACT/SAT** https://www.cde.ca.gov/ds/sp/ai/ (files: 2019-20 ACT, 2018-19 ACT, 2017-18 ACT)
* **A-G** https://www.cde.ca.gov/ta/ac/cm/datafiles2020.asp (files: datafiles2019.asp, datafiles2018.asp, datafiles2017.asp)
* **CTE** https://www.cde.ca.gov/ta/ac/cm/datafiles2020.asp (files: datafiles2019.asp, datafiles2018.asp, datafiles2017.asp)
* **CAASPP** https://caaspp-elpac.cde.ca.gov/caaspp/ResearchFileList?ps=true&lstTestYear=2019&lstTestType=B&lstCounty=00&lstDistrict=00000&lstSchool=0000000#dl (files 2016-17, 2018-19, 2019-20)
* **AP/IB** 
* **Graduation** https://www.cde.ca.gov/ds/ad/filesacgr.asp (files: acgr20, acgr19, acgr18, acgr17)
* **Suspension** https://www.cde.ca.gov/ds/ad/filessd.asp (files: suspension20, suspension19, suspension18, suspension17, suspension16)
* **College Enrollment** https://www.cde.ca.gov/ds/ad/filescgr12.asp (files: cgr12mo18, cgr12mo17, cgr12mo16)

##### Local Data (see data sharing agreement)
* **GPA** 
* **ASB**
* **Clubs**
* **Parent Involvement** 
* **Detention/Referrals**
* **Mental Health Services**
* **School Recognition** 

#### Data collection dates:

Database URLs were retrieved from the CDE website between October 19, 2021 – November 22, 2021


### DATA DICTIONARY
Note continue building out the dictionary as we define data elements.

#### Variables for final output CSV file, assistance.csv, and then used for the analyses:

* **Year** = the year the demographic and assessment information counts in XXXX format.
                 
* **Enrl** = the count of students enrolled in the LEA for years 2015-2019.   
     
* **l_Enrl** = the log count of students enrolled in the LEA for years 2015-2019. Enrollment is transformed so that it shares a more similar scale to other variables.

* **FRPM_shr** = the proportion of students who receive a free or reduced priced lunch.

* **EL_shr** = the proportion of students identified as an English Learner.

* **SDI_prop** = a demographic index score on a 0 to 1 scale. The School Demographic Index is a score that reflects the level of diversity in an LEA. The index is calculated by determining the proportion of each of the 8 major race/ethnicity subgroups in an LEA. An LEA with 100% of one subgroup would have a score closer to 0. An LEA with a score closer to 100 would have an equal distribution of all 8 subgroups. This index provides a sense of how diverse an LEA is and also allows for comparisons between similar LEAs in terms of diversity. Diversity, however, does not account for program participation, which can also be an important factor in the conditions of schooling. Program participation is captured by free and reduced lunch proportions and proportions of English Learners.

* **Masters_shr** = a proportion of teachers with masters degrees in the LEA.

* **Avg_teach** = the average years of teaching experience in the LEA.

* **ADA** = a proportion that represents the average daily attendance rate in an LEA. A .96 indicates that 96% of students attend school in the LEA daily.

* **Revenue** = the annual revenue of the LEA.

* **l_Revenue** = the log of annual revenue of the LEA. The log is calculated to standardize variable scales.

* **StudentsTested** = the count of students tested in the LEA.

* **l_StudentsTested** = the log count of students tested in the LEA.

* **CAASPPEnrollment** = the count of the students enrolled in testing in the LEA. This number reflects the number of students who should have tested. The difference between this number and StudentsTested reflects how many students opted out of state testing.

* **l_CAASPPEnrollment** = the log count of the students enrolled in testing in the LEA.

* **Grade** = the grade level indicator of students for the particular assessment. 

* **MScaleScore** = the scale score for the particular assessment and grade level.

* **TestId** = a content area indicator either Math or ELA.

* **NCESDist** = the alphanumeric federal identifier of the LEA.

* **District** = the name of the LEA.

### DATA ANALYSIS

#### Program used:
* R version R version 4.0.3 (2020-10-10)
* RStudio 1.3.1093
* Platform: x86_64-w64-mingw32 (64-bit)
* Running under: Windows 10
* Attached base packages:
  * stats
  * graphics
  * devices
  * utils
  * datasets 
  * methods
  * base     
* Other attached packages:
  * dplyr
  * purrr
  * readxl
  * tidyr
  * ggplot2 
  * tidyverse
  * stringr
  * lubridate
  * stringr
  * stringi
  * knitr
  * magrittr

#### There are xx scripts that work sequentially:

**01_equity_download.Rmd** Purpose: Loop through and download each of the data files associated with final ***equity.csv***.

  * Package(s): knitr, dplyr, lubridate, here, purr, tidyverse, readxl, stringr, stringi, magrittr
  
  * Input file(s): lcff_assistance.csv, lcff_assistance.xlsx, LCFF_Prority4.xlsx, public_schools.txt, Revenue1415.txt, sacs1415.mdb, sacs1516.mdb, sacs11617.mdb, sacs1718.mdb, sacs1819.mdb, sb_ca2015_all_csv_v3.txt, sb_ca2016_all_csv_v3.txt, sb_ca2017_all_csv_v3.txt, sb_ca2018_all_csv_v3.txt, sb_ca2019_all_csv_v3.txt, sb_ca2015entities_csv.txt, sb_ca2016entities_csv.txt, sb_ca2017entities_csv.txt, sb_ca2018entities_csv.txt, sb_ca2019entities_csv.txt, sch_demo_1617.txt, sch_demo_1718.txt, sch_demo_1819.txt, sch_el_1516.txt, sch_el_1617.txt, sch_el_1718.txt, sch_el_1819.txt, StaffDemo14.txt, StaffDemo14.txt, StaffDemo15.txt, StaffDemo16.txt, StaffDemo17.txt, StaffDemo18.txt, stu_ada_1415, stu_ada_1516, stu_ada_1617, stu_ada_1718, stu_ada_1819, stu_foster_1415, stu_foster_1516, stu_foster_1617, stu_foster_1718, stu_foster_1819, stu_poverty_1415, stu_poverty_1516, stu_poverty_1617, stu_poverty_1718, stu_poverty_1819, UserGL1415.txt, UserGL1516.txt, UserGL1617.txt, UserGL1718.txt, UserGL1819.txt,
   
   * Output file(s): 

**02_equity_import.Rmd** Purpose: Import the combined datasets and merge into one master file.

  * Package(s): knitr, dplyr, lubridate, here, purr, tidyverse, readxl, stringr, stringi, magrittr
  * Input file(s): 
  * Output file(s): 

**03_equity_tidy.Rmd** Purpose: Explore and clean dataset. 

   * Package(s): knitr, dplyr, ggplot, readr, tidyverse
   * Input file(s): 
   * Output file(s): **equity.csv**


### SHARING & ACCESSING INFORMATION

* **Formally:** Creative Commons Open Source (CC0) to facilitate ease-of-use
* **Informally:** The citation is:


### ADDITIONAL NOTES/COMMENTS

Please let me know if any errors in the dataset are found. 
